# Generated by Django 4.2.5 on 2023-11-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100)),
                ('presion_arterial', models.CharField(max_length=100)),
                ('temperatura', models.CharField(max_length=100)),
                ('pulso', models.CharField(max_length=100)),
                ('nivel_oxigeno_sangre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden_medicamentos', models.CharField(max_length=100)),
                ('nombre_medicamneto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('cedula_medico', models.CharField(max_length=100)),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('sintomatologia', models.CharField(max_length=100)),
                ('dianostico', models.CharField(max_length=100)),
                ('numero_orden_medicamentos', models.CharField(max_length=100)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('numero_orden_procedimiento', models.CharField(max_length=100)),
                ('nombre_procedimiento', models.CharField(max_length=100)),
                ('cantidad_procedimento', models.CharField(max_length=100)),
                ('frecuencia_procedimiento', models.CharField(max_length=100)),
                ('requiere_asistencia_especialista', models.CharField(max_length=100)),
                ('numero_orden_dianostico', models.CharField(max_length=100)),
                ('nombre_dianostico', models.CharField(max_length=100)),
                ('cantidad_dianostico', models.CharField(max_length=100)),
                ('requiere_asistencia_dianostico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('relacion_paciente', models.CharField(max_length=100)),
                ('numero_emergencia', models.CharField(max_length=100)),
                ('nombre_compania_seguros', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(max_length=100)),
                ('estado_poliza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=100)),
            ],
        ),
    ]
